export const nouns = [
  { word: "apple", hint: "A red or green fruit" },
  { word: "car", hint: "A four-wheeled vehicle" },
  { word: "book", hint: "You read this" },
  { word: "computer", hint: "Used to browse the internet" },
  { word: "dog", hint: "A barking pet" },
  { word: "cat", hint: "A meowing pet" },
  { word: "house", hint: "You live in it" },
  { word: "school", hint: "Place to study" },
  { word: "teacher", hint: "Helps students learn" },
  { word: "student", hint: "Learns at school" },
  { word: "phone", hint: "Used to call or text" },
  { word: "table", hint: "You eat on it" },
  { word: "chair", hint: "You sit on it" },
  { word: "pen", hint: "Writes with ink" },
  { word: "pencil", hint: "Writes and can be erased" },
  { word: "clock", hint: "Tells the time" },
  { word: "watch", hint: "Worn on wrist" },
  { word: "window", hint: "Lets you see outside" },
  { word: "door", hint: "You open this to enter" },
  { word: "bed", hint: "You sleep on it" },
  { word: "lamp", hint: "Used for light" },
  { word: "shirt", hint: "Upper body clothing" },
  { word: "pants", hint: "Lower body clothing" },
  { word: "hat", hint: "Worn on the head" },
  { word: "shoe", hint: "Worn on the foot" },
  { word: "sock", hint: "Worn under shoes" },
  { word: "cup", hint: "Used to drink from" },
  { word: "bottle", hint: "Holds liquid" },
  { word: "plate", hint: "Food is served on it" },
  { word: "fork", hint: "Used to eat food" },
  { word: "spoon", hint: "Used for soup" },
  { word: "knife", hint: "Used to cut food" },
  { word: "water", hint: "You drink it" },
  { word: "milk", hint: "White drink from cows" },
  { word: "bread", hint: "Baked food item" },
  { word: "butter", hint: "Goes on bread" },
  { word: "cheese", hint: "Made from milk" },
  { word: "egg", hint: "Comes from chickens" },
  { word: "meat", hint: "Comes from animals" },
  { word: "fish", hint: "Lives in water" },
  { word: "bird", hint: "Has feathers and flies" },
  { word: "cow", hint: "Gives milk" },
  { word: "horse", hint: "You can ride it" },
  { word: "pig", hint: "Oinks on a farm" },
  { word: "chicken", hint: "Lays eggs" },
  { word: "duck", hint: "Quacks and swims" },
  { word: "zoo", hint: "Animals live here" },
  { word: "forest", hint: "Many trees grow here" },
  { word: "river", hint: "Flows with water" },
  { word: "mountain", hint: "Very tall and rocky" },
  { word: "beach", hint: "Sandy place near ocean" },
  { word: "island", hint: "Land in the sea" },
  { word: "city", hint: "Big town" },
  { word: "village", hint: "Small town" },
  { word: "road", hint: "Cars drive on it" },
  { word: "street", hint: "Smaller than a road" },
  { word: "bus", hint: "Big vehicle for people" },
  { word: "train", hint: "Runs on tracks" },
  { word: "plane", hint: "Flies in the sky" },
  { word: "boat", hint: "Floats on water" },
  { word: "bike", hint: "Has two wheels" },
  { word: "engine", hint: "Powers a vehicle" },
  { word: "garage", hint: "Where cars sleep" },
  { word: "garden", hint: "Plants grow here" },
  { word: "tree", hint: "Tall and green" },
  { word: "flower", hint: "Colorful plant" },
  { word: "grass", hint: "Green and on the ground" },
  { word: "leaf", hint: "Part of a tree" },
  { word: "fruit", hint: "Sweet plant food" },
  { word: "vegetable", hint: "Healthy plant food" },
  { word: "banana", hint: "Yellow curved fruit" },
  { word: "orange", hint: "Citrus fruit and a color" },
  { word: "grape", hint: "Tiny purple or green fruit" },
  { word: "melon", hint: "Large round fruit" },
  { word: "berry", hint: "Small juicy fruit" },
  { word: "camera", hint: "Takes photos" },
  { word: "television", hint: "Shows movies and news" },
  { word: "radio", hint: "Plays music" },
  { word: "music", hint: "You listen to it" },
  { word: "song", hint: "A musical piece" },
  { word: "game", hint: "You play it" },
  { word: "ball", hint: "Round object for sports" },
  { word: "toy", hint: "Children play with it" },
  { word: "child", hint: "A young person" },
  { word: "baby", hint: "Very young child" },
  { word: "family", hint: "Parents and children" },
  { word: "mother", hint: "Female parent" },
  { word: "father", hint: "Male parent" },
  { word: "brother", hint: "Male sibling" },
  { word: "sister", hint: "Female sibling" },
  { word: "friend", hint: "Someone you like" },
  { word: "neighbor", hint: "Lives near you" },
  { word: "doctor", hint: "Helps sick people" },
  { word: "nurse", hint: "Assists the doctor" },
  { word: "police", hint: "Keeps people safe" },
  { word: "fireman", hint: "Fights fires" },
  { word: "worker", hint: "Has a job" },
  { word: "farmer", hint: "Grows food" },
  { word: "cook", hint: "Makes food" },
  { word: "waiter", hint: "Brings food to tables" },
  { word: "artist", hint: "Makes paintings" },
  { word: "singer", hint: "Performs songs" },
  { word: "actor", hint: "Plays in movies" },
  { word: "driver", hint: "Controls a vehicle" },
  { word: "pilot", hint: "Flies planes" },
  { word: "engineer", hint: "Designs machines" },
  { word: "scientist", hint: "Studies science" },
  { word: "student", hint: "Learns at school" },
  { word: "homework", hint: "Work from school" },
  { word: "exam", hint: "A test of knowledge" },
  { word: "grade", hint: "Score in school" },
  { word: "class", hint: "Group of students" },
  { word: "subject", hint: "Area of study" },
  { word: "math", hint: "Numbers and equations" },
  { word: "history", hint: "Study of the past" },
  { word: "science", hint: "Study of nature" },
  { word: "english", hint: "Language subject" },
  { word: "letter", hint: "Part of the alphabet" },
  { word: "word", hint: "Unit of language" },
  { word: "sentence", hint: "Group of words" },
  { word: "paragraph", hint: "Group of sentences" },
  { word: "story", hint: "Tells what happened" },
  { word: "poem", hint: "Rhyming story" },
  { word: "journal", hint: "Personal writing" },
  { word: "notebook", hint: "Used to write notes" },
  { word: "paper", hint: "You write on it" },
  { word: "eraser", hint: "Removes pencil marks" },
  { word: "bag", hint: "Carries items" },
  { word: "backpack", hint: "Worn on the back" },
  { word: "money", hint: "Used to buy things" },
  { word: "coin", hint: "Round metal money" },
  { word: "dollar", hint: "US currency" },
  { word: "card", hint: "Plastic payment tool" },
  { word: "shop", hint: "Place to buy things" },
  { word: "store", hint: "Sells products" },
  { word: "market", hint: "Place with sellers" },
  { word: "mall", hint: "Big shopping place" },
  { word: "bank", hint: "Keeps your money" },
  { word: "hospital", hint: "Where sick people go" },
  { word: "clinic", hint: "Smaller than a hospital" },
  { word: "office", hint: "Workplace with desks" },
  { word: "company", hint: "Business organization" },
  { word: "factory", hint: "Makes products" },
  { word: "job", hint: "Work you do" },
  { word: "boss", hint: "Gives you orders" },
  { word: "meeting", hint: "Work gathering" },
  { word: "holiday", hint: "Day off" },
  { word: "vacation", hint: "Time to relax" },
  { word: "weekend", hint: "Saturday and Sunday" },
  { word: "day", hint: "24 hours" },
  { word: "night", hint: "Dark part of the day" },
  { word: "morning", hint: "Early in the day" },
  { word: "evening", hint: "Late in the day" },
  { word: "hour", hint: "60 minutes" },
  { word: "minute", hint: "60 seconds" },
  { word: "second", hint: "Short time unit" },
  { word: "calendar", hint: "Shows the date" },
  { word: "year", hint: "12 months" },
  { word: "month", hint: "About 30 days" },
  { word: "week", hint: "7 days" }
];